
project_id = "mpjcflpgrvtixxtajhdl"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://aicareeradvisor.lovable.app"
additional_redirect_urls = ["https://aicareeradvisor.lovable.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true

# Define the Edge Functions
[functions]
port = 54321

[functions.analyze-file]
verify_jwt = true

[functions.generate-ai-response]
verify_jwt = true
