// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpjcflpgrvtixxtajhdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wamNmbHBncnZ0aXh4dGFqaGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTc2MzksImV4cCI6MjA2MzIzMzYzOX0.khBACPu_k5WjD0qLrTbN5GzoG_xwB2W5BjNpOe1Or3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);